### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by jrdodds** [johnverbiest/TransformOnBuild#8]
The link in the readme file for the Microsoft documentation is pointing to the VS2015 documentation. The VS2022 equivalent link is [Code Generation in a Build Process](https://learn.microsoft.com/en-us/visualstudio/modeling/code-generation-in-a-build-process?view=vs-2022&tabs=csharp).

Text Templating (T4) is now separate from the Modeling SDK. It is its own install component in the Visual Studio Installer named "Text Template Transformation".

**Comment by johnverbiest** [comment]
Updated the link
